first commit in this branch

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -40,7 +40,7 @@ jobs:
         run: terraform plan -no-color -input=false
         continue-on-error: true
 
-      - name: Update Pull Request
+      - name: Update Pull Request #This step helps in providing real-time feedback on the pull request with detailed results from the Terraform execution. It enhances the review process by making the relevant information easily accessible to reviewers.
         uses: actions/github-script@v6 #Script Execution: You provide a JavaScript script that runs within the workflow. This script can use the GitHub API to perform various actions, such as creating comments, updating issues, or querying repository data
         if: github.event_name == 'pull_request'
         env:
@@ -72,8 +72,8 @@ jobs:
 
       - name: Terraform Plan Status
         if: steps.plan.outcome == 'failure'
-        run: exit 1
+        run: exit 1 #If the Terraform plan fails, this step will fail the workflow, ensuring that further steps are not executed.
 
       - name: Terraform Apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false
+        run: terraform apply -auto-approve -input=false #If the changes are pushed to the main branch, this step will apply the Terraform plan automatically.
